### ISSUE TITLE
"End of Central Directory record could not be found."- 0.0.6-beta1

### ISSUE THREAD

**Issue by 1100594** [clarkis117/Mime-Detective#16] opened 2018-03-22 19:22 UTC
Hi @clarkis117,

I've updated the nuget to version **0.0.6-beta1** and now I'm getting the following error "End of Central Directory record could not be found" with a byte array of a Excel file.

**Sample of code:** `File.ReadAllBytes(filePath).GetFileType()`

**Sample of file:** [test.xlsx](https://github.com/clarkis117/Mime-Detective/files/1838954/test.xlsx)

**TargetFramework:** .NET Core 2.0

Could you help me with this?

Additionally, do you have any expected date for the final nuget release of the 0.0.6?

Thank you,

**Comment by clarkis117** [comment] 2018-03-22 22:25
Thank you for the bug report, the issue was being caused by using the incorrect array length in the ZipFileAnalyzer class. ReadResult.ReadLength was being incorrectly used when creating a MemoryStream in the ZipFileAnalyzer class. I updated the documentation that it's intended to max out at 560, and that when Analyzers are referring to whole files passed as arrays they should use ReadResult.Array.Length instead of ReadResult.ReadLength.

I just merged the fix, and the new version (0.0.6-beta2) should be up on NuGet.

**Comment by clarkis117** [comment] 2018-03-22 22:30
@1100594  As for release plans, I still need to update many of the doc comments to reflect changes for 0.0.6, post benchmarks and usage guidelines for the new trie-based algs, update the markdown page for the GitHub repo, and review the test cases to ensure there aren't anymore major gaps like this. I'm thinking maybe by next weekend.

**Closed** 2018-03-27 21:59 UTC
Labels: bug
